python train.py \
--data_path /home/jonatas/datasets/ \
--data_name faster_precomp \
--adapt_data faster_precomp \
--adapt_split val \
--adapt_batch_size 1 \
--val_data faster_precomp \
--val_split val \
--max_violation \
--bi_gru \
--agg_func=Mean \
--cross_attn=i2t \
--lambda_softmax=4 \
--num_epochs=20 \
--lr_update=10 \
--learning_rate=.0005 \
--logger_name runs/default/
